### ISSUE TITLE
Hot spots in vertex index table

### ISSUE THREAD

**Issue by youzp** [rayokota/hgraphdb#50]
hi, Vertex Index Table has 20 regions, and the pre-partitioning strategy is hexStringSplit. The design principle of Rowkey is lowercase characters with lexicographical order. However, rowkey always has a fixed prefix of "4", hbase appears hot spots. It is normal when querying data.
```
private val VERTEX_LABEL_MAP = immutable.HashMap[Int, String](
    0 -> "0VertexLabel",
    1 -> "1VertexLabel",
    2 -> "2VertexLabel",
    3 -> "3VertexLabel",
    4 -> "4VertexLabel",
    5 -> "5VertexLabel",
    6 -> "6VertexLabel",
    7 -> "7VertexLabel",
    8 -> "8VertexLabel",
    9 -> "9VertexLabel",
    10 -> "aVertexLabel",
    11 -> "bVertexLabel",
    12 -> "cVertexLabel",
    13 -> "dVertexLabel",
    14 -> "eVertexLabel",
    15 -> "fVertexLabel",
    16 -> "0aVertexLabel",
    17 -> "1bVertexLabel",
    18 -> "3cVertexLabel",
    19 -> "4dVertexLabel"
  )
private val VERTEX_LABEL_MAP_LEN = VERTEX_LABEL_MAP.size

// add index
for (i<-0 until(VERTEX_LABEL_MAP_LEN)) {
    val vertexRegion = VERTEX_LABEL_MAP.get(i).getOrElse("0VertexLabel")
    graph.createIndex(ElementType.VERTEX, vertexRegion, "name", true)
}

// insert vertex
val testName = "test"
val labelIndex = Math.abs(LongHashFunction.farmUo().hashChars(testName)) % VERTEX_LABEL_MAP_LEN
val labelRegion = VERTEX_LABEL_MAP.get(labelIndex.toInt).getOrElse("0VertexLabel")

loader.addVertex(T.id, vertexId, T.label, labelRegion, "name", testName)
```

**Comment by rayokota** [comment]
Yes, it is possible to get hotspots when using vertex indices with many vertices with the same label.  Currently the vertex index is not hashed/salted in order to support range queries and pagination on vertex indices.  It would be possible in the future to add an option to create vertex indices that do not support range queries and pagination, so that they can be salted.

**Comment by youzp** [comment]
@rayokota  thanks for your help. I do not need range queries and pagination, is there any simple way to solve this problem now? I used a different label but it didn't work.

**Comment by rayokota** [comment]
I've modified the vertex index format so that the combination of label and property key is salted.  This will still mean hotspots if you use the same label and property key, but should otherwise distribute vertex indices among region servers.  You will need to drop and recreate any existing vertex indices.

**Comment by teenyboy** [comment]
but how can i design the label  when I presplit the hbase table by HexStringSplit style ? the system don't need the range query and pagination . 
Thank you for taking the time to answer me!

**Comment by rayokota** [comment]
@teenyboy , unfortunately, if you frequently use the same label and property key for a vertex index, you may encounter hotspots.
